[package]
name = "starcoin-move-compiler"
version = "1.9.1"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.41"
once_cell = "1.8.0"
tempfile = "3.1.0"
regex = { version = "1.4.3", default-features = false, features = ["std", "perf"] }
move-compiler = { package="move-compiler", git = "https://github.com/starcoinorg/diem", rev="eda7f1d40ff76b003f0635658ad11eb974a760ee"  }
move-command-line-common = {git = "https://github.com/starcoinorg/diem", rev="eda7f1d40ff76b003f0635658ad11eb974a760ee"}
move-binary-format = { git = "https://github.com/starcoinorg/diem", rev="eda7f1d40ff76b003f0635658ad11eb974a760ee"  }
petgraph = "0.5.1"
walkdir = "2.3"
rayon = "1.5.1"
itertools = "0.10.3"
starcoin-crypto = { path = "../../commons/crypto"}
starcoin-vm-types = { path = "../types"}
starcoin-logger = { path = "../../commons/logger"}

[dev-dependencies]
stest = {path = "../../commons/stest"}
