[package]
name = "starcoin-abi-decoder"
version = "1.9.1"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
serde = { version = "1.0.130", features = ["derive", "rc"] }
serde_bytes = "0.11"
anyhow = "1.0.41"
once_cell = "1.8.0"
hex = "0.4.3"
move-binary-format = {git = "https://github.com/starcoinorg/diem", rev="eda7f1d40ff76b003f0635658ad11eb974a760ee"  }
starcoin-resource-viewer = {path = "../../vm/resource-viewer"}
starcoin-vm-types = { path = "../../vm/types" }
starcoin-abi-types = {path = "../types"}
starcoin-abi-resolver = {path = "../resolver"}
bcs-ext = {path = "../../commons/bcs_ext"}
bcs = "0.1"
schemars = {git = "https://github.com/starcoinorg/schemars", rev="463aa92b0bdb20304906759f43fd5803f0ab2ff6"}
